@startuml
'https://plantuml.com/class-diagram

class Game{
        - players: Player[]
        - board Board
        - rules
        + getBoard()
        + endGame()
}

interface PieceRules{
        + ruleCondition()
}

class CheckMate implements PieceRules{
        + ruleCondition()
}

class Piece{
        - color: Color
        - initialPosition: Position
        + actualPosition: Position
        - isAlive: boolean
        - hasMoved: boolean
        + isAlive(): boolean
        + getColor(): Color
        + getPosition(): Position
        + move(Board board): void
}

class Board {
        - xCord: int
        - yCord: int
        - piece: Piece
        + getX()
        + getY()
        + getPiece()
}

class Player {
        - turn: boolean
        - color: Color
        + pieces[]: Piece
        + deadPieces[]: Piece
        + movement (piece Piece, pos Position): void
}

Enum Color {
        BLACK
        WHITE
}

Enum PieceType  {
        PAWN
        ROOK
        KNIGHT
        BISHOP
        QUEEN
        KING
}


interface Movement {
        + move(pos Position): void

}

class MoveUp implements Movement{
        + move(pos Position): void
}

class MoveDown implements Movement{
        + move(pos Position): void
}

class MoveRight implements Movement{
        + move(pos Position): void
}

class MoveLeft implements Movement{
        + move(pos Position): void
}


Player --> Color
Board --> Movement
PieceRules--> Board
Player --> Piece
Board o-- Piece
Piece -> Color
Game *--- PieceRules
Game *--- Player
Game o--- Board
Piece --> PieceType
@enduml